# Generated by Django 5.2.15 on 2026-07-27 21:20

import conserjeria.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='conserjeria.edificio')),
            ],
            options={
                'ordering': ['edificio', 'numero'],
                'unique_together': {('edificio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_comunes', to='conserjeria.edificio')),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'ordering': ['nombre'],
                'unique_together': {('edificio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='NumeroEstacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='conserjeria.edificio')),
            ],
            options={
                'verbose_name': 'N° Estacionamiento',
                'verbose_name_plural': 'Estacionamientos de Visita (Catálogo)',
                'ordering': ['numero'],
                'unique_together': {('edificio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, validators=[conserjeria.validators.validar_rut])),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='conserjeria.departamento')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mudanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_mudanza', models.DateField()),
                ('responsable', models.CharField(max_length=150)),
                ('hora_inicio', models.TimeField()),
                ('comentario', models.TextField(blank=True)),
                ('conserje_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudanzas', to='conserjeria.departamento')),
            ],
            options={
                'verbose_name': 'Mudanza',
                'verbose_name_plural': 'Mudanzas',
                'ordering': ['dia_mudanza', 'hora_inicio'],
                'indexes': [models.Index(fields=['departamento', 'dia_mudanza'], name='conserjeria_departa_dec808_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstacionamientoVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20)),
                ('conductor', models.CharField(max_length=150)),
                ('fecha_hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10)),
                ('conserje_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estacionamientos_entrada', to=settings.AUTH_USER_MODEL)),
                ('conserje_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionamientos_salida', to=settings.AUTH_USER_MODEL)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_estacionamiento', to='conserjeria.departamento')),
                ('numero_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conserjeria.numeroestacionamiento')),
            ],
            options={
                'verbose_name': 'Estacionamiento de Visita',
                'verbose_name_plural': 'Estacionamientos de Visita',
                'ordering': ['-fecha_hora_entrada'],
                'indexes': [models.Index(fields=['departamento_destino', '-fecha_hora_entrada'], name='conserjeria_departa_15161f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_EDIFICIO', 'Administrador de Edificio'), ('CONSERJE', 'Conserje')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[conserjeria.validators.validar_rut])),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 9 dígitos numéricos (ej: 912345678).', regex='^\\d{9}$')])),
                ('correo', models.EmailField(max_length=254)),
                ('numero_emergencia', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 9 dígitos numéricos (ej: 912345678).', regex='^\\d{9}$')])),
                ('contacto_emergencia', models.CharField(max_length=150)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='conserjeria.edificio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'indexes': [models.Index(fields=['edificio', 'rol'], name='conserjeria_edifici_7dc4d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservaAreaComun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reserva', models.DateField()),
                ('responsable', models.CharField(max_length=150)),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('comentario', models.TextField(blank=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='conserjeria.areacomun')),
                ('conserje_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='conserjeria.departamento')),
            ],
            options={
                'verbose_name': 'Reserva de Área Común',
                'verbose_name_plural': 'Reservas de Áreas Comunes',
                'ordering': ['dia_reserva', 'hora_inicio'],
                'indexes': [models.Index(fields=['departamento', 'dia_reserva'], name='conserjeria_departa_eb16d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=10)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('conserje_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_entregados', to=settings.AUTH_USER_MODEL)),
                ('conserje_recibe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='conserjeria.departamento')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_destinatario', to='conserjeria.residente')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_retirados', to='conserjeria.residente')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetería',
                'ordering': ['-fecha_recepcion'],
                'indexes': [models.Index(fields=['departamento', '-fecha_recepcion'], name='conserjeria_departa_9562b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visita', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, validators=[conserjeria.validators.validar_rut])),
                ('dia_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('conserje_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='conserjeria.departamento')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-dia_visita', '-hora_visita'],
                'indexes': [models.Index(fields=['departamento', '-dia_visita'], name='conserjeria_departa_0bacb9_idx')],
            },
        ),
    ]
