# Generated by Django 5.2.15 on 2026-08-01 14:15

import conserjeria.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conserjeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaareacomun',
            name='conserje_confirma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaareacomun',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de garantía'), ('CONFIRMADA', 'Confirmada')], default='CONFIRMADA', max_length=10),
        ),
        migrations.AddField(
            model_name='reservaareacomun',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaareacomun',
            name='rut_responsable',
            field=models.CharField(blank=True, default='', max_length=12, validators=[conserjeria.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='reservaareacomun',
            name='conserje_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BloqueHorarioAreaComun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('TODOS', 'Todos los días'), ('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='TODOS', max_length=5)),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to='conserjeria.areacomun')),
            ],
            options={
                'verbose_name': 'Bloque de Horario Disponible',
                'verbose_name_plural': 'Bloques de Horario Disponible',
                'ordering': ['area_comun', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
