# Generated by Django 5.2.15 on 2026-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conserjeria', '0002_reservaareacomun_conserje_confirma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='duracion_maxima_horas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Máximo de horas SEGUIDAS por reserva (ej. 2 para el gimnasio). Déjalo vacío si no hay límite (ej. quincho).', null=True),
        ),
    ]
