# Generated by Django 4.2.18 on 2026-08-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conserjeria', '0006_lavadora_lecturalavadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavadora',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturalavadora',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
