# Generated by Django 4.2.18 on 2026-08-07 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conserjeria', '0007_alter_lavadora_id_alter_lecturalavadora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='monto_garantia',
            field=models.PositiveIntegerField(blank=True, help_text='Monto de la garantía en pesos chilenos (sin decimales). Obligatorio si "requiere pago" está marcado.', null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='requiere_pago',
            field=models.BooleanField(default=False, help_text='Si está marcado, la reserva pública exige pago online antes de confirmarse.'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='codigo_comercio_webpay',
            field=models.CharField(blank=True, help_text='Código de comercio hijo entregado por Transbank (Webpay Plus Mall). Vacío si el edificio aún no está afiliado.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='edificio',
            name='garantia_reembolsable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=26, unique=True)),
                ('token_ws', models.CharField(blank=True, default='', max_length=64)),
                ('monto', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado (esperando pago en Transbank)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado (no completado / expirado)'), ('REEMBOLSADO', 'Reembolsado')], default='INICIADO', max_length=11)),
                ('codigo_autorizacion', models.CharField(blank=True, default='', max_length=20)),
                ('respuesta_json', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_reembolso', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='conserjeria.reservaareacomun')),
            ],
            options={
                'verbose_name': 'Pago de Reserva',
                'verbose_name_plural': 'Pagos de Reservas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='conserjeria_estado_711ba6_idx')],
            },
        ),
    ]
