# Generated by Django 4.2.18 on 2026-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conserjeria', '0008_areacomun_monto_garantia_areacomun_requiere_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='modulo_consulta_estacionamiento',
            field=models.BooleanField(default=False, help_text='Habilita la consulta pública (sin login) de estacionamientos de visita libres en este momento.', verbose_name='Módulo: Consulta pública de disponibilidad de estacionamientos de visita'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='modulo_lavadoras',
            field=models.BooleanField(default=False, help_text='Habilita que el comando consultar_lavadoras procese las lavadoras de este edificio.', verbose_name='Módulo: Monitoreo de lavadoras (IoT)'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='modulo_reservas',
            field=models.BooleanField(default=False, help_text='Habilita el formulario público de reservas y el cobro online (Webpay) de la garantía.', verbose_name='Módulo: Reserva y pago de áreas comunes'),
        ),
    ]
