"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY_")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUGS", default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
ADMIN_URL = config('ADMIN_URL', default='admin/')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'conserjeria',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'conserjeria.middleware.EdificioMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 2  # horas
AXES_LOCKOUT_TEMPLATE = None
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ---------------------------------------------------------------------------
# DATOS DE BASE DE DATOS (DATABASES)
# ---------------------------------------------------------------------------


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization


LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Autenticación
LOGIN_URL = 'conserjeria:login'
LOGIN_REDIRECT_URL = 'conserjeria:home_redirect'
LOGOUT_REDIRECT_URL = 'conserjeria:login'


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Seguridad  DEJAR VALORES EN .ENV SIN DEFINIR PARA PODER DESARROLLAR EN LOCAL

#SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
#CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
#SECURE_BROWSER_XSS_FILTER = True
#SECURE_CONTENT_TYPE_NOSNIFF = True

#CSRF_COOKIE_HTTPONLY = True 

#SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
#SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 año
#SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
#SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
#SECURE_REFERRER_POLICY = "same-origin"


# ---------------------------------------------------------------------------
# WEBPAY PLUS MALL (Transbank) -- pago online de la garantía de reservas.
#
# WEBPAY_COMMERCE_CODE es el código de comercio "padre" del Mall que integra
# la plataforma (uno solo, tuyo). Los códigos "hijo" son por edificio y
# viven en Edificio.codigo_comercio_webpay, no acá.
#
# Los defaults son las credenciales públicas de INTEGRACIÓN que publica
# Transbank en su documentación (no son secretas, sirven para cualquier
# desarrollador) -- así el proyecto funciona en local/dev sin tocar nada.
# En producción, WEBPAY_ENVIRONMENT=LIVE y las credenciales reales SIEMPRE
# vienen del EnvironmentFile de systemd, nunca hardcodeadas.
# ---------------------------------------------------------------------------
WEBPAY_COMMERCE_CODE = config('WEBPAY_COMMERCE_CODE', default='597055555535')
WEBPAY_API_KEY = config(
    'WEBPAY_API_KEY', default='579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
)
# TEST (integración) o LIVE (producción, requiere afiliación real con Transbank).
WEBPAY_ENVIRONMENT = config('WEBPAY_ENVIRONMENT', default='TEST')
# Minutos que se le da al residente para completar el pago en Transbank
# antes de que el management command de barrido libere el horario.
WEBPAY_MINUTOS_EXPIRACION_PAGO = config('WEBPAY_MINUTOS_EXPIRACION_PAGO', default=20, cast=int)
